services:
  redis:
    image: ${REDIS_IMAGE:-redis:7-alpine}
    volumes:
      - redis:/data

  usershub:
    image: ${USERSHUB_IMAGE:-ghcr.io/pnx-si/usershub:latest}
    volumes:
      - ./config/usershub/:/dist/config/
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - USERSHUB_URL_APPLICATION="${USERSHUB_PROTOCOL:-http}://${USERSHUB_HOST}${USERSHUB_PREFIX:-/}"
      - USERSHUB_SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - USERSHUB_SETTINGS=${USERSHUB_SETTINGS:-config.py}
      - PYTHONPATH=/dist/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usershub.rule=Host(`${USERSHUB_HOST}`) && PathPrefix(`${USERSHUB_PREFIX:-/}`)"
      - "traefik.http.routers.usershub.entrypoints=web"

  taxhub:
    image: ${TAXHUB_IMAGE:-ghcr.io/pnx-si/taxhub:latest}
    volumes:
      - ./config/taxhub/:/dist/config/
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - TAXHUB_APPLICATION_ROOT="${TAXHUB_PREFIX:-/}"
      - TAXHUB_SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - TAXHUB_SETTINGS=${TAXHUB_SETTINGS:-config.py}
      - PYTHONPATH=/dist/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taxhub.rule=Host(`${TAXHUB_HOST}`) && PathPrefix(`${TAXHUB_PREFIX:-/}`)"
      - "traefik.http.routers.taxhub.entrypoints=web"

  geonature-worker:
    image: ${GEONATURE_BACKEND_IMAGE:-ghcr.io/pnx-si/geonature-backend:latest}
    depends_on:
      - redis
    volumes:
      - ./config/geonature/:/dist/config/
    user: ${UID:-1000}:${GID:-1000}
    env_file:
      - geonature.env
    command: celery -A geonature.celery_app:app worker

  geonature-backend:
    image: ${GEONATURE_BACKEND_IMAGE:-ghcr.io/pnx-si/geonature-backend:latest}
    depends_on:
      - redis
    volumes:
      - ./config/geonature/:/dist/config/
    user: ${UID:-1000}:${GID:-1000}
    env_file:
      - geonature.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature-api.rule=Host(`${GEONATURE_BACKEND_HOST}`) && PathPrefix(`${GEONATURE_BACKEND_PREFIX:-/}`)"
      - "traefik.http.routers.geonature-api.entrypoints=web"

  geonature-frontend:
    image: ${GEONATURE_FRONTEND_IMAGE:-geonature-frontend}
    build:
      context: ./GeoNature/
      dockerfile: ./frontend/Dockerfile
      target: prod-full
    environment:
      - NGINX_LOCATION=${GEONATURE_FRONTEND_PREFIX:-/}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature.rule=Host(`${GEONATURE_FRONTEND_HOST}`) && PathPrefix(`${GEONATURE_FRONTEND_PREFIX:-/}`)"
      - "traefik.http.routers.geonature.entrypoints=web"

volumes:
  redis:
