version: "3.9"

x-defaults: &defaults
  user: ${UID:-1000}:${GID:-1000}

x-geonature-backend-defaults: &geonature-backend-defaults
  <<: *defaults
  environment:
    - GEONATURE_SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
    - GEONATURE_URL_APPLICATION="${GDS_GEONATURE_FRONTEND_PROTOCOL}://${GDS_GEONATURE_FRONTEND_HOST}${GDS_GEONATURE_FRONTEND_PREFIX:-}"
    - GEONATURE_API_ENDPOINT="${GDS_GEONATURE_BACKEND_PROTOCOL}://${GDS_GEONATURE_BACKEND_HOST}${GDS_GEONATURE_BACKEND_PREFIX:-/}"
    - GEONATURE_API_TAXHUB="${GDS_TAXHUB_PROTOCOL}://${GDS_TAXHUB_HOST}${GDS_TAXHUB_API_PREFIX}"
    - GEONATURE_CONFIG_FILE=${GEONATURE_CONFIG_FILE:-/dist/config/geonature_config.toml}
    - GEONATURE_STATIC_FOLDER=${GEONATURE_STATIC_FOLDER:-/dist/static}
    - GEONATURE_CUSTOM_STATIC_FOLDER=${GEONATURE_CUSTOM_STATIC_FOLDER:-/dist/custom}
    - GEONATURE_MEDIA_FOLDER=${GEONATURE_MEDIA_FOLDER:-/dist/geonature_media}
    - GEONATURE_CELERY__broker_url=${GEONATURE_CELERY__broker_url:-redis://redis}
    - GEONATURE_CELERY__result_backend=${GEONATURE_CELERY__result_backend:-redis://redis}
    - srid_local=${GEONATURE_SRID_LOCAL-2154}
    - GEONATURE_POPULATE_DB=${GEONATURE_POPULATE_DB:-true}
    - add_sample_data=${GEONATURE_ADD_SAMPLE_DATA:-false}
    - install_bdc_statuts=${GEONATURE_INSTALL_BDC_STATUTS:-true}
    - install_sig_layers=${GEONATURE_INSTALL_SIG_LAYERS:-false}
    - install_grid_layer=${GEONATURE_INSTALL_GRID_LAYER:-false}
    - install_ref_sensitivity=${GEONATURE_INSTALL_REF_SENSITIVITY:-false}
    - install_default_dem=${GEONATURE_INSTALL_DEFAULT_DEM:-false}
    - vectorise_dem=${GEONATURE_INSTALL_VECTORISE_DEM:-false}
    - usershub=${GEONATURE_INSTALL_USERSHUB:-true}
    - usershub_samples=${GEONATURE_INSTALL_USERSHUB_SAMPLES:-true}
    - taxhub=${GEONATURE_INSTALL_TAXHUB:-true}
    - taxhub_samples=${GEONATURE_INSTALL_TAXHUB_SAMPLES:-true}

services:
  redis:
    image: ${REDIS_IMAGE:-redis:7-alpine}
    volumes:
      - redis:/data

  postgres:
    image: ${POSTGRES_IMAGE:-postgis/postgis:13-3.2}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_INIT_DB_DIR-./sources/GeoNature/install/assets/db}:/docker-entrypoint-initdb.d/
      - ${GDS_POSTGRES_DIRECTORY:-./data/db/postgres}:/var/lib/postgresql/data
  usershub:
    <<: *geonature-backend-defaults
    image: ${GDS_USERSHUB_IMAGE:-ghcr.io/pnx-si/usershub:latest}
    depends_on:
      - postgres
    volumes:
      - ${GDS_USERSHUB_CONFIG_DIRECTORY:-./data/apps/usershub/config}:/dist/config/
    environment:
      - USERSHUB_URL_APPLICATION="${GDS_USERSHUB_PROTOCOL:-http}://${GDS_USERSHUB_HOST}${GDS_USERSHUB_PREFIX:-/usershub}"
      - USERSHUB_SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - USERSHUB_SECRET_KEY=${USERSHUB_SECRET_KEY:-ABCDEFGH123}
      - USERSHUB_SETTINGS=${USERSHUB_SETTINGS:-/dist/config/config.py}
      - USERSHUB_ACTIVATE_APP=${USERSHUB_ACTIVATE_APP:-true}
      - USERSHUB_ACTIVATE_API=${USERSHUB_ACTIVATE_API:-true}
      - USERSHUB_COOKIE_EXPIRATION=${USERSHUB_COOKIE_EXPIRATION:-3600}
      - PYTHONPATH=/dist/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usershub.rule=Host(`${GDS_USERSHUB_DOMAIN}`) && PathPrefix(`${GDS_USERSHUB_PREFIX:-/usershub}`)"
      - "traefik.http.routers.usershub.entrypoints=web"

  taxhub:
    <<: *geonature-backend-defaults
    image: ${GDS_TAXHUB_IMAGE:-ghcr.io/pnx-si/taxhub:latest}
    depends_on:
      - postgres
    volumes:
      - ${GDS_TAXHUB_CONFIG_DIRECTORY:-./data/apps/taxhub/config}:/dist/config
      - ${GDS_TAXHUB_STATIC_DIRECTORY:-./data/apps/taxhub/static}:/dist/static
    environment:
      - TAXHUB_APPLICATION_ROOT="${GDS_TAXHUB_PREFIX:-/taxhub}"
      - TAXHUB_SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - TAXHUB_SETTINGS=${TAXHUB_SETTINGS:-config.py}
      - PYTHONPATH=/dist/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taxhub.rule=Host(`${GDS_TAXHUB_DOMAIN}`) && PathPrefix(`${GDS_TAXHUB_PREFIX:-/taxhub}`)"
      - "traefik.http.routers.taxhub.entrypoints=web"

  geonature-worker:
    <<: *geonature-backend-defaults
    image: ${GDS_GEONATURE_BACKEND_IMAGE:-ghcr.io/pnx-si/geonature-backend:latest}
    depends_on:
      - redis
      - postgres
    volumes:
      - ${CONFIG_DIRECTORY:-./data/apps/geonature/config}:/dist/config/
    command: celery -A geonature.celery_app:app worker

  geonature-backend:
    <<: *geonature-backend-defaults
    image: ${GDS_GEONATURE_BACKEND_IMAGE:-ghcr.io/pnx-si/geonature-backend:latest}
    depends_on:
      - redis
      - postgres
    volumes:
      - ${GDS_GEONATURE_CONFIG_DIRECTORY:-./data/apps/geonature/config}:/dist/config
      - ${GDS_GEONATURE_MEDIA_DIRECTORY:-./data/apps/geonature/media}:/dist/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature-backend.rule=Host(`${GDS_GEONATURE_DOMAIN}`) && PathPrefix(`${GDS_GEONATURE_BACKEND_PREFIX:-/geonature/api}`)"
      - "traefik.http.routers.geonature-backend.entrypoints=web"
  geonature-frontend:
    image: ${GDS_GEONATURE_FRONTEND_IMAGE:-ghcr.io/pnx-si/geonature-frontend:latest}
    environment:
      - NGINX_LOCATION=${GDS_GEONATURE_FRONTEND_PREFIX:-/}
      - API_ENDPOINT="${GDS_GEONATURE_BACKEND_PROTOCOL}://${GDS_GEONATURE_BACKEND_HOST}${GDS_GEONATURE_BACKEND_PREFIX:-/}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geonature.rule=Host(`${GDS_GEONATURE_DOMAIN}`) && PathPrefix(`${GDS_GEONATURE_FRONTEND_PREFIX:-/}`)"
      - "traefik.http.routers.geonature.entrypoints=web"

  traefik:
    image: traefik:2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${GDS_HTTP_PORT:-80}:80
      - ${GDS_HTTPS_PORT:-443}:443

volumes:
  redis:
  postgres: