services:
  usershub:
    ports:
      - 5001:5001

  taxhub:
    ports:
      - 5000:5000

  geonature-backend:
    ports:
      - 8000:8000

  geonature-frontend:
    image: ${GEONATURE_FRONTEND_IMAGE:-node:16-bullseye}
    working_dir: /home/node/app
    volumes:
      - ./GeoNature/frontend:/home/node/app
    command: "npm run start -- --poll 2000 --disable-host-check"
    expose:
      - "4200"
    ports:
      - 4200:4200
