version: "3.7"

services:

  traefik:
    image: traefik:2.1.1
    command:
     - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certs:/var/traefik/certs/"
      - "traefik-logs:/var/log/traefik/"
      - "./traefik-config.yml.tmp:/etc/traefik/traefik.yml"
    networks:
      web:

networks:
  web:
    external: true

volumes:
  traefik-certs:
  traefik-logs:
