version: "3.7"
services:

  postgres:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "raw-data:/data/"
    networks:
      - databases

networks:
  databases:
    external: true

volumes:
  postgres-data:
  raw-data:
    external: true
