version: "3.7"
services:

  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.local
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "raw-data:/data/"
    networks:
      - databases

  adminer:
    image: adminer:4.7.5
    ports:
      - "8000:8080"
    networks:
      databases:

networks:
  databases:
    external: true

volumes:
  postgres-data:
  raw-data:
    external: true