version: "3.7"

services:
  redis:
    restart: unless-stopped
    image: redis:7.0
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - databases

networks:
  databases:
    external: true